defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - vscodium.code-workspace
  - Gemfile*

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag